$schema: "http://json-schema.org/draft-06/schema#"

description: snakemake configuration file

type: object

properties:
  rnaseq_program_params:
    type: string

  rnaseq_samples:
    type: string

required:
  - rnaseq_program_params
  - rnaseq_samples
