import pandas as pd
import yaml
from os.path import join

from snakemake.utils import min_version
from snakemake.utils import validate

min_version("5.1")

# -- configuration

# ---- global snakemake config

validate(config, "conf_schemas/snake_config.schema.yaml")

# ---- definition of samples for study here

def define_rnaseq_samples(filepath):
    rnaseq_samples = pd.read_csv(
        filepath, sep = "\t", comment="#"
    ).set_index(
        ["study_id", "sample_id", "run_id", "lane_id"], drop = False
    )
    rnaseq_samples.index = rnaseq_samples.index.set_levels(
        [i.astype(str) for i in rnaseq_samples.index.levels]
    )
    return rnaseq_samples


rnaseq_samples = define_rnaseq_samples(config["rnaseq_samples"])
validate(rnaseq_samples, "conf_schemas/rnaseq_samples.schema.yaml")


# ---- definition of command line params for the programs used here

rnaseq_program_params = yaml.safe_load(
    open(config["rnaseq_program_params"], "r")
)
validate(
    rnaseq_program_params, "conf_schemas/rnaseq_program_params.schema.yaml"
)


# -- targets of the current workflow-step

trimmed_fastq_files = expand(
    join(
        "data", "job", "trimmed_fastqs", "{unit.study_id}", "{unit.sample_id}",
        "{unit.run_id}_{unit.lane_id}_{read}.fastq.gz"
    ),
    unit=rnaseq_samples.itertuples(),
    read=[1, 2]
)

required_files = []

# -- rules

rule all:
    input:
        required_files + ["doc/fake_report.pdf"]

rule faker:
    output:
        "doc/fake_report.pdf"
    shell:
        """
        touch doc/fake_report.pdf
        """


# -- imported rules

include: "scripts/snake_recipes/access_raw_reads.smk"
include: "scripts/snake_recipes/trim.smk"
